
interface UserInfo {
  name: string;
  email: string;
  institution: string;
  level: string;
  chapter: string;
}

export const generateLatexTemplate = (userInfo: UserInfo): string => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `\\documentclass[12pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{geometry}
\\usepackage{amsmath}
\\usepackage{amsfonts}
\\usepackage{amssymb}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage{fancyhdr}
\\usepackage{setspace}

% Page setup
\\geometry{margin=1in}
\\pagestyle{fancy}
\\fancyhf{}
\\rhead{${userInfo.name}}
\\lhead{${userInfo.institution}}
\\cfoot{\\thepage}

% Title setup
\\title{Academic Document\\\\
\\large Generated by LaTeX Magic}
\\author{${userInfo.name}\\\\
\\texttt{${userInfo.email}}\\\\
\\textit{${userInfo.institution}}}
\\date{${currentDate}}

% Document settings
\\onehalfspacing
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{1em}

\\begin{document}

\\maketitle

\\begin{abstract}
This document was automatically generated using LaTeX Magic, a professional document generation tool for academic and research purposes. The content below represents the chapter or section material provided by ${userInfo.name}, a ${userInfo.level} at ${userInfo.institution}.
\\end{abstract}

\\newpage

\\section{Introduction}

This document has been prepared for ${userInfo.name}, who is currently at the ${userInfo.level} level at ${userInfo.institution}. The following section contains the main content as provided by the author.

\\section{Main Content}

${userInfo.chapter}

\\section{Conclusion}

This document demonstrates the power of automated LaTeX generation for academic and professional documentation. The LaTeX Magic tool provides a streamlined workflow for creating well-formatted documents that meet academic standards.

\\section{Document Information}

\\begin{itemize}
    \\item \\textbf{Author:} ${userInfo.name}
    \\item \\textbf{Email:} \\texttt{${userInfo.email}}
    \\item \\textbf{Institution:} ${userInfo.institution}
    \\item \\textbf{Academic Level:} ${userInfo.level}
    \\item \\textbf{Generated:} ${currentDate}
    \\item \\textbf{Tool:} LaTeX Magic PDF Maker
\\end{itemize}

\\vfill

\\hrule
\\vspace{0.5em}
\\begin{center}
\\small Generated automatically by LaTeX Magic \\\\
Professional document generation for academics and researchers
\\end{center}

\\end{document}`;
};
